name: hangman
description: Well known word guess game, a simple version

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.1
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^4.0.5
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  easy_localization: ^3.0.2
  flutter_riverpod: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon/logo.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
